import React from "react";
import {
  View,
  Text,
  ScrollView,
  SafeAreaView,
  StatusBar,
  TouchableOpacity,
  Alert,
} from "react-native";
import { useRouter } from "expo-router";
import { Printer } from "lucide-react-native";
import * as Print from "expo-print";
import * as Sharing from "expo-sharing";
import "../../global.css";
import Colors from "../../constants/Colors";
import CustomHeader from "../../components/CustomHeader";

export default function ServiceReportScreen() {
  const router = useRouter();
  const monthsGroup = [
    ["श्रावण", "भाद्र", "आश्विन", "कार्तिक"],
    ["मंसिर", "पौष", "माघ", "फाल्गुन"],
    ["चैत्र", "बैशाख", "जेष्ठ", "आषाढ"]
  ];

  const handlePrint = async () => {
    try {
      const htmlContent = `
        <!DOCTYPE html>
        <html>
          <head>
            <meta charset="utf-8">
            <style>
              body { 
                font-family: sans-serif; 
                padding: 40px;
                color: #1a202c;
              }
              .header {
                text-align: center;
                margin-bottom: 40px;
              }
              .title {
                font-size: 22px;
                font-weight: bold;
                line-height: 1.4;
              }
              .divider {
                width: 100px;
                height: 4px;
                background-color: ${Colors.primary || '#0056D2'};
                margin: 15px auto;
                border-radius: 2px;
              }
              .table-container {
                display: flex;
                width: 100%;
                border: 1px solid #718096;
              }
              .column-group {
                flex: 1;
                border-right: 2px solid #4a5568;
              }
              .column-group:last-child {
                border-right: none;
              }
              table {
                width: 100%;
                border-collapse: collapse;
              }
              th, td {
                border: 1px solid #718096;
                padding: 12px 8px;
                text-align: center;
                font-size: 13px;
              }
              th {
                background-color: #f7fafc;
                font-weight: bold;
              }
              .month-cell {
                background-color: #f7fafc;
                font-weight: bold;
                width: 80px;
              }
              .empty-cell {
                height: 80px;
              }
              .footer {
                margin-top: 40px;
                font-size: 11px;
                color: #718096;
                text-align: center;
                font-style: italic;
              }
            </style>
          </head>
          <body>
            <div class="header">
              <div class="title">महिला स्वास्थ्य स्वयंसेविकाले सेवा पुर्याएका जम्मा सेवाग्राहीको संख्या</div>
              <div class="divider"></div>
            </div>

            <div class="table-container">
              ${monthsGroup.map((group) => `
                <div class="column-group">
                  <table>
                    <thead>
                      <tr>
                        <th>महिना</th>
                        <th>सेवाग्राही</th>
                        <th>जम्मा</th>
                      </tr>
                    </thead>
                    <tbody>
                      ${group.map((month) => `
                        <tr>
                          <td class="month-cell">${month}</td>
                          <td class="empty-cell"></td>
                          <td></td>
                        </tr>
                      `).join('')}
                    </tbody>
                  </table>
                </div>
              `).join('')}
            </div>

            <div class="footer">
              Generated by FCHV Saathi App | महिला स्वास्थ्य स्वयंसेविका साथी
            </div>
          </body>
        </html>
      `;

      const { uri } = await Print.printToFileAsync({ html: htmlContent });
      await Sharing.shareAsync(uri, { UTI: '.pdf', mimeType: 'application/pdf' });
    } catch (error) {
      console.error(error);
      Alert.alert("Error", "Failed to generate print document.");
    }
  };

  const TableHeader = () => (
    <View className="flex-row border-b border-slate-300 bg-slate-50">
      <View className="w-[60px] p-2 border-r border-slate-300 items-center justify-center">
        <Text className="font-bold text-[10px] text-slate-700">महिना</Text>
      </View>
      <View className="flex-1 p-2 border-r border-slate-300 items-center justify-center">
        <Text className="font-bold text-[10px] text-slate-700">सेवाग्राही</Text>
      </View>
      <View className="w-[40px] p-2 items-center justify-center">
        <Text className="font-bold text-[10px] text-slate-700">जम्मा</Text>
      </View>
    </View>
  );

  const TableRow = ({ month }: { month: string }) => (
    <View className="flex-row border-b border-slate-300 min-h-[100px]">
      <View className="w-[60px] p-2 border-r border-slate-300 items-center justify-center bg-slate-50/30">
        <Text className="text-[11px] font-bold text-slate-800 text-center">{month}</Text>
      </View>
      <View className="flex-1 p-2 border-r border-slate-300 items-center justify-center">
        <View className="w-full h-[1px] bg-slate-100 my-2" />
        <View className="w-full h-[1px] bg-slate-100 my-2" />
        <View className="w-full h-[1px] bg-slate-100 my-2" />
      </View>
      <View className="w-[40px] p-2 items-center justify-center">
        <Text className="text-[11px] text-slate-300"></Text>
      </View>
    </View>
  );

  return (
    <SafeAreaView className="flex-1 bg-white">
      <StatusBar barStyle="dark-content" />
      <CustomHeader 
        title="रिपोर्ट (Report)" 
        onBackPress={() => router.replace("/dashboard/report")}
        rightNode={
          <TouchableOpacity 
            onPress={handlePrint}
            className="p-2 bg-blue-50 rounded-xl"
          >
            <Printer size={20} color={Colors.primary || "#0056D2"} />
          </TouchableOpacity>
        }
      />

      <ScrollView 
        className="flex-1" 
        contentContainerStyle={{ paddingBottom: 40 }}
        showsVerticalScrollIndicator={false}
      >
        <View className="p-4">
          <View className="items-center mb-6 px-2">
            <Text className="text-[17px] font-black text-slate-900 text-center leading-tight">
              महिला स्वास्थ्य स्वयंसेविकाले सेवा पुर्याएका जम्मा सेवाग्राहीको संख्या
            </Text>
            <View className="w-16 h-1 bg-primary rounded-full mt-2" />
          </View>

          <ScrollView horizontal showsHorizontalScrollIndicator={false}>
            <View className="border border-slate-300 rounded-lg overflow-hidden bg-white shadow-sm">
              <View className="flex-row">
                {monthsGroup.map((group, groupIdx) => (
                  <View key={groupIdx} className={`w-[260px] ${groupIdx < 2 ? 'border-r-2 border-slate-400' : ''}`}>
                    <TableHeader />
                    {group.map((month, idx) => (
                      <TableRow key={idx} month={month} />
                    ))}
                  </View>
                ))}
              </View>
            </View>
          </ScrollView>

          <View className="mt-8 p-4 bg-slate-50 rounded-2xl border border-slate-100">
            <Text className="text-slate-500 text-[11px] font-medium leading-relaxed">
              सूचना: यो तालिका महिला स्वास्थ्य स्वयंसेविकाको मासिक कार्यसम्पादन र सेवाग्राहीहरूको संख्या अभिलेख राख्न प्रयोग गरिन्छ । प्रति महिनाको विवरण प्रविष्टि गर्नुहोस् ।
            </Text>
          </View>

        </View>
      </ScrollView>
    </SafeAreaView>
  );
}
